name: Snap Creative
favicon: null
layout_spectrum: 0.7245019036345184
typography_spectrum: 0.7330075071658939
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3422298601362854
  lightness: 0.6657526979688555
  saturation: 0.18010711879469454
  rhythmicContrast: 0.14355484931729734
purpose: []
